export const document_types = [
  'Will',
  'Advance Healthcare Directive',
  'Insurance Policies',
  'Trust',
  'Tax Returns',
  'Deeds/Mortgages',
  'Year-End Statements',
  'Birth Certificates',
  'Passport',
  'Marriage License',
  'Divorce Papers',
  'Home Improvement Documentation And Receipts',
  'Receipts For Major Purchases (Warranties)',
  'Power Of Attorney Designations',
  'Medical And Burial Instructions',
  'Real Estate Certificates',
  'Auto Titles',
  'Medical Records',
  'Education Records',
  'Pension Plan Records',
  'Retirement Plan Records',
];
