const ROUTES = {
  //  BASE_URL:"https://778mpekjkk.execute-api.us-east-1.amazonaws.com/stage",
  // BASE_URL: "https://weh4nnvk0g.execute-api.us-east-1.amazonaws.com/stage02",
  BASE_URL: "https://devapi.assetplanet.com",
  // BASE_URL:"https://efze03zxt4.execute-api.us-east-1.amazonaws.com/stage02",
  // BASE_URL: "http://192.168.100.32:3000/dev",
  // BASE_URL: "http://192.168.100.32:3000/stage02",
  // BASE_URL: "http://localhost:3000/stage02",
  // BASE_URL: "http://192.168.100.29:3000/stage02",
  // BASE_URL: "http://192.168.100.32:3000/stage02",



  FETCH_ALL_MODULES: "module/all",
  FETCH_ALL_ITEMS: "client-module/list",
  DELETE_ITEM: "client-module",
  FETCH_ALL_ROOMS: "client-module/detail",
  FETCH_FAQ: "faq/all",
  CREATE_MODULE: "module",
  UPDATE_MODULE: "module",
  SWAP_COLLECTIBLES: "module/swap",
  MODULE_ATTRIBUTES: "attribute/detail",
  REMOVE_MODULE_ATTRIBUTES: "module/attribute/remove",
  IMAGE_UPLOAD: "upload/file",
  CRETE_CLIENT_ITEM: "client-module",
  UPDATE_CLIENT_ITEM: "client-module/update",
  RECORD_TOTAL: "client-module/total",
  ASSET_FIELDS: "attribute/detail",
  FETCH_ALL_ASSET_ALLOCATION: "module/asset-allocation",
  PERSONAL_INSTRUCTIONS: "client/personalInstructions",
  CONTACT_LIST: "client/contact",
  PASSWORDS: "client/passwords",
  PREPAID_BURIAL: "client/prepaidBurialExpense",
  BILLS_TO_PAY: "client/billsToPay",
  LITIGATION: "client/litigation",
  ACCOUNT_ASSET: "client/accountAsset",
  PERSONAL_ITEM_LOCATION: "client/itemLocation",
  CLIENTS_POLICIES: "client/policies",
  CLIENTS_DOCUMENTS: "client/clientDocuments",
  CHECKLIST: "client/checklist",
  SPOUSEINFO: "client-spouse",
  DEPENDENT_DETAILS: "client-dependent",
  TRUST_INFO: "client-trust",
  CORPORATE_INFO: "client-corporate",
  CHARITY_INFO: "client-charity",
  OTHER_IMPACTS: "client-other-impact",
  CREATE_SPOUSE: "client-spouse",
  CREATE_DEPENDENT: "client-dependent",
  CREATE_TRUST_INFO: "client-trust",
  CREATE_CORPORATE_INFO: "client-corporate",
  CREATE_CHARITY_INFO: "client-charity",
  CREATE_OTHER_IMPACTS: "client-other-impact",
  UPDATE_SPOUSE_INFO: "client-spouse",
  EMAIL_TO_SEND: 'client/emails',
  TEXTS_TO_SEND: 'client/texts',
  AUDIO_VIDEO: 'client/audio-video',
  UPDATE_DEPENDENT_INFO: "client-dependent",
  UPDATE_TRUST_INFO: "client-trust",
  UPDATE_CORPORATE_INFO: "client-corporate",
  UPDATE_CHARITY_INFO: "client-charity",
  UPDATE_OTHER_IMPACTS: "client-other-impact",
  DELETE_SPOUSE_INFO: "client-spouse",
  DELETE_DEPENDENT_INFO: "client-dependent",
  DELETE_TRUST_INFO: "client-trust",
  DELETE_CORPORATE_INFO: "client-corporate",
  DELETE_CHARITY_INFO: "client-charity",
  DELETE_OTHER_IMPACTS: "client-other-impact",
  ACCOUNT_ASSET_Liabilities: "client-module",
  DOWNLOAD_TEMPLATE: "export-csv",
  UPLOAD_DOCUMENT: "upload-csv",
  EXPORT_DOCUMENT: "export-csv",
  OTP_VERIFY: "auth/verifyOTP",
  OTP_CONFIG: "send-otp-in-death",
  CONFIRM_DEATH: "confirm-death",
  DEATH_STATUS: "client-death-status",
  REVERT_DEATH: "revert-death-status",
  POST_VIDEO: "signedUrl",
  POST_TEMPLATE: "email-template",
  TIMER: "death-status-revert-time",
  CLIENT_LIST: "clients-for-delegation-access",
  ADVANCE_HEALTH: "advance-healthCare-directive",
  SEND_EMAIL: "send-email-and-text",
  DEATH_CERTIFICATE: "death-certificate-url",
  TEXT_TEMPLATE: "text-template",
  SECOND_PASSWORD: "second-password-granted",
  CLIENT_FUNERAL: "client-funeral-information",
  EMAIL_LOGS: "client/emailLogs",
  EMAIL_LOGS_COUNT: "client/emailLogCounts",



};

export default ROUTES;
